### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by JustSxm** [git-shawn/Rerouter#2]
This is a suggestion to add to the name what the app does eg: "Google Maps to Plans" or "Safari Extension", something similar.

This would allow users to find the app more easily as of right now it wont be found in the app store unless specific keywords are used. Even then, they paid variants will be shown to the users first.

PS: It is way more tempting to donate than to pay for the app :)

**Comment by git-shawn** [comment]
Thank you so much for the suggestion! I've edited the App Store listing name in the new update to say "Rerouter - Open links in Maps".
