### ISSUE TITLE
Hide icon in Safari toolbar

### ISSUE THREAD

**Issue by idnovic** [git-shawn/Rerouter#3]
Rerouter icon resets itself after safari is restarted.
If I hide the rerouter icon over the "edit toolbar" menu, it only stays hidden until safari is restarted.

Steps to reproduce:
1. Edit the safari toolbar and hide the rerouter icon by moving it out of the toolbar
2. Restart safari
3. Rerouter icon reappears

What should happen:
The rerouter icon should stay hidden.

**Comment by git-shawn** [comment]
While the extension itself can't control its appearance in the toolbar, this bug appears to have been fixed by the Safari team. However, it may reappear after an app update—there's currently no way to prevent that.
