### ISSUE TITLE
Support for country-specific Google domains

### ISSUE THREAD

**Issue by katagaki** [git-shawn/Rerouter#4]
Currently, Rerouter seems to support only 'google.com', however, there may be a chance that Google Maps may open a country-specific domain (e.g. [https://www.google.co.jp/maps/...](https://www.google.co.jp/maps/dir/日本、東京都千代田区丸の内１丁目９+東京駅/長崎県,+日本/@33.2488329,129.6230511,12z/data=!4m13!4m12!1m5!1m1!1s0x60188bfbd89f700b:0x277c49ba34ed38!2m2!1d139.7671248!2d35.6812362!1m5!1m1!1s0x3569a110b1af8e0b:0x24952a1ea9084a95!2m2!1d129.6930912!2d33.2488525) ). Rerouter does not redirect these links at the moment.

A list of supported domains by Google is provided here: [https://www.google.com/supported_domains](https://www.google.com/supported_domains)

**Comment by git-shawn** [comment]
Thanks for opening this issue! This has been fixed in the latest commit.
