### ISSUE TITLE
Bug when opening shared Google maps links 

### ISSUE THREAD

**Issue by lennon1997** [git-shawn/Rerouter#5]
When opening Google maps links formatted like https://maps.app.goo.gl/h7g3ricUnbRTuyXx7?g_st=i
from messages or other apps the extension will not trigger unless I swipe up to show the list view of the route. 

I believe it’s because the link leads to https://www.google.com/maps?geocode=Ff___38d____fyk7CD_TpU_CiTFi_nfhBo8LyA%3D%3D;Ff___38d____fym_KlaRZXbBiDHQTsdb0xMu9w%3D%3D&daddr=Florida,+United+States&saddr=New+York,+USA&dirflg=d&ftid=0x89c24fa5d33f083b:0xc80b8f06e177fe62;0x88c1766591562abf:0xf72e13d35bc74ed0&g_ep=CAISBjYuMzcuMRgAIJScAQ%3D%3D&g_st=i&g_st=i first and then to https://www.google.com/maps/dir/New+York,+USA/Florida,+United+States/@34.1910626,-77.8457165,4z/data=!4m8!4m7!1m2!1m1!1s0x89c24fa5d33f083b:0xc80b8f06e177fe62!1m2!1m1!1s0x88c1766591562abf:0xf72e13d35bc74ed0!3e0

**Comment by git-shawn** [comment]
The latest commit and iOS update should fix this problem. Thanks!
